-- Migrates the 3 posts previously hardcoded in src/lib/posts.ts into the
-- database (now the source of truth, see migration 0036), plus 3 new posts.
-- Idempotent: safe to re-run.

insert into blog_posts (slug, title, description, published_at, body) values (
  'momentum-score-methodology',
  'How we score competitor momentum (and why it excludes SEO data)',
  'The math behind Ripplewatch''s Momentum score: four signal types rolled into one directional number, and why we deliberately leave a fifth one out for now.',
  '2026-08-12',
  '[{"type":"p","text":"Every competitor page in Ripplewatch shows a Momentum badge — Heating up, Steady, Cooling, or Not enough history yet. It''s meant to answer one question at a glance: is this competitor accelerating or slowing down right now? Here''s exactly how it''s computed."},{"type":"h2","text":"Four inputs, one 30-day window"},{"type":"p","text":"Momentum compares two adjacent 30-day windows — the last 30 days versus the 30 before that — across four signal types Ripplewatch already tracks:"},{"type":"ul","items":["Hiring — job posting volume","Pricing activity — pricing page changes","Press & funding — news and funding events","Relevance trend — how the average relevance score of scored signals is moving"]},{"type":"p","text":"Each component is converted into a bounded, symmetric index from -100 to +100: zero means no change between windows, and the score approaches ±100 as activity swings entirely into one window or the other. A small smoothing constant keeps a single new signal (one this month, zero last month) from immediately maxing out the score the way a raw percentage-change calculation would."},{"type":"h2","text":"Why SEO/traffic isn''t in the mix yet"},{"type":"p","text":"We track a fifth signal type — SEO/traffic activity — but it''s currently a stubbed data source and only available on Plus and Advanced plans. Folding a stub into Momentum would make the score meaningless for Starter accounts and simply wrong for everyone else until real traffic data is wired in. So Momentum only averages the components that actually have data for a given competitor, and a competitor with zero signals in both windows across all four components shows \"Not enough history yet\" instead of a misleading zero."},{"type":"h2","text":"The thresholds"},{"type":"p","text":"The final score is the average of whichever components have data. Above +15, we label it Heating up. Below -15, Cooling. Everything in between is Steady. Those thresholds are intentionally conservative — a single noisy week of hiring shouldn''t flip a competitor''s label back and forth."},{"type":"p","text":"This is also why Momentum shows up in two places — the Trends dashboard and the Competitors list badge — pulling from the exact same calculation, so the two views never drift into disagreeing about the same competitor."}]'::jsonb
) on conflict (slug) do nothing;

insert into blog_posts (slug, title, description, published_at, body) values (
  'win-loss-reason-consolidation',
  'Why we stopped showing raw win/loss dumps',
  'A CSV import with 800+ win/loss rows is data. Nobody can read it. Here''s how we turned it into a two-column, top-5 summary — deterministically, with no LLM call.',
  '2026-08-12',
  '[{"type":"p","text":"Import a CRM''s win/loss export into Ripplewatch and you can easily end up with hundreds of rows — one per deal, each with a canned reason your reps picked from a CRM dropdown: \"Price\", \"Missing feature\", \"Lost to incumbent\", and a handful of variations. The raw list is complete, but nobody actually reads 800 rows to find a pattern."},{"type":"h2","text":"Group by exact text, not by meaning"},{"type":"p","text":"The obvious fix is to summarize the reasons — and the obvious tool for summarizing freeform text is an LLM. We didn''t use one here, on purpose. CRM win/loss reasons are close-ended in practice: they come from a fixed dropdown, so \"Price\" and \"price\" and \" Price \" are the same reason typed slightly differently, not three genuinely different reasons that need semantic clustering. Grouping by exact text (trimmed, case-insensitive) does the job, and it''s deterministic and free — no API call, no risk of an LLM inventing a category that isn''t in the data."},{"type":"p","text":"That''s a real distinction we draw elsewhere in the product too: Trends, which looks for patterns across genuinely freeform text like call notes, does use the model. Win/loss reasons don''t need it."},{"type":"h2","text":"Top 5, not all of them"},{"type":"p","text":"Once reasons are grouped and tallied, we rank win reasons and loss reasons independently — a reason can legitimately show up on both sides, if it''s mostly why you win but has cost you a couple of deals too — and cap each column at the top 5, with a \"+N more\" indicator and a thin proportional bar per row. The full raw list is still there, one click away behind a \"Show all N individual entries\" toggle, for anyone who wants to audit the underlying data."},{"type":"h2","text":"One component, two places"},{"type":"p","text":"This view is the same component in two spots: on each competitor''s fact sheet (scoped to deals against that one competitor) and on an account-wide Win/Loss page (aggregated across all of them). Same grouping logic, same layout, same 5-item cap — so switching between \"how do we do against Competitor X\" and \"how do we do overall\" doesn''t mean learning a different UI."}]'::jsonb
) on conflict (slug) do nothing;

insert into blog_posts (slug, title, description, published_at, body) values (
  'why-some-pricing-pages-cant-be-scraped',
  'Why some competitor pricing pages can''t be scraped — and how to tell which',
  'Not all scraping blocks are the same. A field diagnosis of Cloudflare JS challenges, Cloudflare WAF blocks, Akamai, and one false alarm.',
  '2026-08-12',
  '[{"type":"p","text":"Ripplewatch tracks competitor pricing pages automatically, and every so often one comes back \"Couldn''t load.\" The instinctive next step is to assume it''s a bot-detection problem and reach for a bigger hammer — rotate IPs, spoof a browser fingerprint, solve the CAPTCHA. We don''t do that. Those techniques cross from \"scraping resiliently\" into evading a site''s explicit access controls, which isn''t something we''re willing to build, regardless of how easy it would make our own product."},{"type":"p","text":"What we do instead is diagnose the actual block before deciding whether there''s a legitimate fix. Requesting a page with our own identified bot user agent (RipplewatchBot, with a link back to us — not spoofed as a browser) and reading the response headers and body tells you which of a few very different things is actually happening."},{"type":"h2","text":"Four outcomes, one curl request"},{"type":"ul","items":["Cloudflare JS challenge — an interstitial \"Just a moment...\" page with a cf-ray header. This is solvable legitimately: a headless browser that executes JavaScript (not a fingerprint-spoofing one) clears it the same way a real visitor''s browser does.","Cloudflare WAF hard block — an explicit \"Attention Required!\" page. This is the site operator deciding automated traffic isn''t welcome at all, full stop. We treat that as a boundary, not an obstacle.","Akamai hard block — \"Access Denied\" with an x-akamai-cache-status header. Similar story to a Cloudflare WAF block: a deliberate access decision, not a technical hurdle to route around.","False positive — the page actually returns a clean 200. In one case, a pricing page we''d flagged as blocked turned out to be a stale status from a transient failure, not a real block at all. Worth checking before assuming the worst."]},{"type":"h2","text":"The honest takeaway"},{"type":"p","text":"Roughly half of scraping failures we''ve diagnosed this way are fixable with better tooling (a real headless browser instead of a plain HTTP request). The other half are a site operator''s explicit choice, and no amount of engineering effort should override that. Distinguishing the two before writing code saves you from building something that either doesn''t work or shouldn''t exist."}]'::jsonb
) on conflict (slug) do nothing;

insert into blog_posts (slug, title, description, published_at, body) values (
  'why-competitive-intelligence-should-always-be-on',
  'Why competitive intelligence should always be on',
  'Most competitive intelligence still runs as sporadic research before a launch or a QBR. Here''s why that''s the wrong shape, and what "always on" actually requires.',
  '2026-08-13',
  '[{"type":"p","text":"At most companies, competitive intelligence isn''t a system — it''s a project. Someone builds a battlecard before a big launch or a board meeting, circulates it, and then it sits untouched until the next fire drill makes someone go looking again. In between, nobody''s watching."},{"type":"h2","text":"The cost of periodic research"},{"type":"p","text":"The problem with periodic research isn''t that it''s low quality — it''s that competitors don''t move on your review calendar. A pricing change, a key hire, a funding round: these happen whenever they happen, and by the time your next scheduled competitive review rolls around, the window where that information could have changed a decision has often already closed. A rep loses a deal to a competitor''s new pricing tier three weeks before anyone on your team notices it exists."},{"type":"h2","text":"What \"always on\" actually requires"},{"type":"p","text":"Continuous monitoring sounds like it just means checking more often, but doing it well requires three separate things, not one:"},{"type":"ul","items":["Continuous data collection — not a snapshot refreshed occasionally, but sources actually watched on a schedule tight enough to matter.","A way to separate signal from noise — more sources watched more often just means more raw material, not more insight, unless something is doing the filtering.","A fast enough path from \"something changed\" to \"here''s what it means\" that the answer is still useful when it arrives, not a historical footnote by the time someone reads it."]},{"type":"h2","text":"The real blocker isn''t tooling, it''s triage"},{"type":"p","text":"Monitoring more sources is, at this point, the easy part — pricing pages, job boards, press feeds, and social channels are all crawlable, and that''s been true for years. The actual hard problem is not burying the one signal that matters under fifty that don''t. A team that turns on monitoring for every competitor across every channel without a way to prioritize what surfaces usually turns it back off within a month, because a noisy feed is worse than no feed at all. That''s the real argument for scoring findings against your specific business, not just collecting more of them: always-on only works if always-on doesn''t mean always-noisy."}]'::jsonb
) on conflict (slug) do nothing;

insert into blog_posts (slug, title, description, published_at, body) values (
  'why-competitive-intelligence-goes-stale',
  'Why most competitive intelligence programs go stale',
  'Battlecards get built once for a launch or a big deal, then rarely touched again. Here''s why maintenance is the part that gets skipped, and what actually keeps intel current.',
  '2026-08-13',
  '[{"type":"p","text":"Walk into most B2B companies and ask to see the competitive battlecard for their top rival. You''ll usually get one — and it''ll usually be six months to a year old, built for a launch or a big deal that''s long since closed, with a pricing table that''s quietly wrong and a \"weaknesses\" section describing a product that''s since shipped the exact feature it says the competitor lacks."},{"type":"h2","text":"Why maintenance is the part that gets skipped"},{"type":"p","text":"Creating a battlecard is a project: it has a deadline (the launch, the QBR, the board deck), an owner, and a clear definition of done. Keeping it accurate afterward is a chore with no deadline, no natural owner, and no moment where anyone declares it finished. Projects get staffed. Chores, in practice, mostly don''t — not because anyone decides competitive intel isn''t worth maintaining, but because nobody ever explicitly decided who''s responsible for noticing when it goes stale."},{"type":"h2","text":"Three ways it actually breaks"},{"type":"ul","items":["No owner after the initial push — whoever built it moves on to the next launch, and updating a document nobody assigned isn''t anyone''s job.","The underlying facts change quietly — a competitor updates their pricing page or ships a feature with no press release, so there''s no trigger that tells anyone to go check.","The team''s attention moves faster than the document does — three priorities later, the battlecard is a relic of what mattered at the time it was written, not what matters now."]},{"type":"h2","text":"What keeps intel current, not just created"},{"type":"p","text":"The fix isn''t more discipline or a recurring calendar reminder — those are exactly the kind of unowned chore that gets skipped the first time someone''s busy. If checking a competitor''s pricing page requires a human to remember to look, it will eventually stop happening; that''s not a character flaw, it''s just how unassigned recurring work behaves in every team. The alternative is removing the manual step entirely: monitor automatically, and only put something in front of a person when it''s actually worth their attention. Staleness stops being a discipline problem the moment it stops depending on someone remembering."}]'::jsonb
) on conflict (slug) do nothing;

insert into blog_posts (slug, title, description, published_at, body) values (
  'competitive-intelligence-in-an-ai-world',
  'What competitive intelligence means in an AI world',
  'AI changed both how fast competitors can move and what''s possible to monitor about them. Here''s what actually changes for competitive intelligence — and what doesn''t.',
  '2026-08-13',
  '[{"type":"p","text":"Two things changed for competitive intelligence at roughly the same time, and it''s worth separating them. Competitors can now ship, reposition, and change pricing faster, because AI tooling compressed their own product cycles. And separately, the tools available for watching them got dramatically more capable, for the same underlying reason."},{"type":"h2","text":"What AI actually changes for the watcher"},{"type":"p","text":"The genuine shift isn''t philosophical, it''s practical — a few specific things that used to require a person now don''t:"},{"type":"ul","items":["Reading and summarizing large volumes of unstructured text — job postings, press coverage, changelogs — cheaply and continuously, instead of a person skimming a handful of sources on a schedule.","Extracting structured facts out of messy pages, like a pricing table or a feature comparison, without someone manually copying numbers into a spreadsheet every time a page changes.","Judging relevance against a specific context — this company''s positioning, this company''s actual win/loss history — instead of applying one generic severity rule to every reader."]},{"type":"h2","text":"What it doesn''t change"},{"type":"p","text":"Judgment about what''s actually true still needs a real source; a model summarizing a rumor still produces a confident-sounding summary of a rumor. And scoring \"does this matter to us\" still requires real context about the reader''s own business — a model can use that context well, but it has to be given it, not invent it from nothing. More capable summarization of bad or biased inputs is still a bad or biased answer, just delivered more fluently."},{"type":"h2","text":"The actual shift"},{"type":"p","text":"The honest framing isn''t \"AI replaces the competitive intelligence analyst.\" It''s that the cost of running continuous, personalized monitoring dropped enough that \"always on, and scored specifically for us\" is now realistic for a five-person go-to-market team, not just something an enterprise with a dedicated competitive intelligence function could justify staffing. That access gap closing is the real change — not that the underlying discipline of competitive intelligence is fundamentally different than it was."}]'::jsonb
) on conflict (slug) do nothing;
