-- Rewrites all 6 blog posts for more natural sentence rhythm (the prior
-- em-dash removal was a mechanical punctuation swap, which left choppy,
-- comma-heavy prose). Same facts and structure, better voice. Idempotent.

update blog_posts set
  title = 'How we score competitor momentum (and why it excludes SEO data)',
  description = 'The math behind Ripplewatch''s Momentum score: four signal types rolled into one directional number, and why we deliberately leave a fifth one out for now.',
  body = '[{"type":"p","text":"Every competitor page in Ripplewatch shows a Momentum badge: Heating up, Steady, Cooling, or Not enough history yet. It answers one question at a glance: is this competitor speeding up or slowing down right now? Here''s exactly how it''s computed."},{"type":"h2","text":"Four inputs, one 30-day window"},{"type":"p","text":"Momentum compares two adjacent 30-day windows (this month against the one before it) across four signal types Ripplewatch already tracks:"},{"type":"ul","items":["Hiring: job posting volume","Pricing activity: pricing page changes","Press & funding: news and funding events","Relevance trend: how the average relevance score of scored signals is moving"]},{"type":"p","text":"Each component turns into a bounded index from -100 to +100. Zero means no change between windows. The score approaches ±100 as activity swings almost entirely into one window or the other. A small smoothing constant keeps a single new signal (one this month, zero last) from immediately maxing out the score the way a raw percentage-change calculation would."},{"type":"h2","text":"Why SEO/traffic isn''t in the mix yet"},{"type":"p","text":"There''s a fifth signal type we track, SEO/traffic activity, but it''s currently a stubbed data source and only available on Plus and Advanced plans. Folding a stub into Momentum would make the score meaningless for Starter accounts, and simply wrong for everyone else, until real traffic data is wired in. So Momentum only averages the components that actually have data for a given competitor. A competitor with zero signals in both windows across all four components shows \"Not enough history yet\" instead of a misleading zero."},{"type":"h2","text":"Where the thresholds land"},{"type":"p","text":"The final score is the average of whichever components have data. Above +15, we call it Heating up. Below -15, Cooling. Everything in between is Steady. Those thresholds are intentionally conservative, so a single noisy week of hiring doesn''t flip a competitor''s label back and forth."},{"type":"p","text":"It''s also why Momentum shows up in two places, the Trends dashboard and the Competitors list badge, pulling from the exact same calculation. The two views can''t drift into disagreeing about the same competitor."}]'::jsonb,
  updated_at = now()
where slug = 'momentum-score-methodology';

update blog_posts set
  title = 'Why we stopped showing raw win/loss dumps',
  description = 'A CSV import with 800+ win/loss rows is data. Nobody can read it. Here''s how we turned it into a two-column, top-5 summary, deterministically, with no LLM call.',
  body = '[{"type":"p","text":"Import a CRM''s win/loss export into Ripplewatch and you can easily end up with hundreds of rows: one per deal, each with a canned reason your reps picked from a dropdown. \"Price.\" \"Missing feature.\" \"Lost to incumbent.\" And a dozen slight variations on each. The raw list is complete. Nobody actually reads 800 rows to find a pattern."},{"type":"h2","text":"Group by exact text, not by meaning"},{"type":"p","text":"The obvious fix is to summarize the reasons, and the obvious tool for summarizing freeform text is an LLM. We didn''t use one here, on purpose. CRM win/loss reasons are close-ended in practice. They come from a fixed dropdown, so \"Price\" and \"price\" and \" Price \" are the same reason typed slightly differently, not three genuinely different reasons that need semantic clustering. Grouping by exact text (trimmed, case-insensitive) does the job. It''s also deterministic and free: no API call, no risk of an LLM inventing a category that isn''t in the data."},{"type":"p","text":"That''s a real distinction we draw elsewhere in the product too. Trends, which looks for patterns across genuinely freeform text like call notes, does use the model. Win/loss reasons just don''t need it."},{"type":"h2","text":"Top 5, not all of them"},{"type":"p","text":"Once reasons are grouped and tallied, we rank win reasons and loss reasons independently. A reason can legitimately show up on both sides if it''s mostly why you win but has cost you a couple of deals too. Each column caps at the top 5, with a \"+N more\" indicator and a thin proportional bar per row. The full raw list is still there, one click away behind a \"Show all N individual entries\" toggle, for anyone who wants to audit the underlying data."},{"type":"h2","text":"One component, two places"},{"type":"p","text":"This view is the same component in two spots: each competitor''s fact sheet (scoped to deals against that one competitor) and an account-wide Win/Loss page (aggregated across all of them). Same grouping logic, same layout, same 5-item cap. Switching between \"how do we do against Competitor X\" and \"how do we do overall\" doesn''t mean learning a different UI."}]'::jsonb,
  updated_at = now()
where slug = 'win-loss-reason-consolidation';

update blog_posts set
  title = 'Why some competitor pricing pages can''t be scraped, and how to tell which',
  description = 'Not all scraping blocks are the same. A field diagnosis of Cloudflare JS challenges, Cloudflare WAF blocks, Akamai, and one false alarm.',
  body = '[{"type":"p","text":"Ripplewatch tracks competitor pricing pages automatically, and every so often one comes back \"Couldn''t load.\" The instinctive next move is to assume it''s a bot-detection problem and reach for a bigger hammer: rotate IPs, spoof a browser fingerprint, solve the CAPTCHA. We don''t do that. Those techniques cross the line from scraping resiliently into evading a site''s explicit access controls, and that''s not something we''re willing to build, no matter how much easier it would make our own product."},{"type":"p","text":"What we do instead is diagnose the actual block before deciding whether there''s a legitimate fix. Requesting a page with our own identified bot user agent (RipplewatchBot, with a link back to us, not spoofed as a browser) and reading the response headers and body tells you which of a few very different things is actually happening."},{"type":"h2","text":"Four outcomes, one curl request"},{"type":"ul","items":["Cloudflare JS challenge: an interstitial \"Just a moment...\" page with a cf-ray header. This one''s solvable legitimately: a headless browser that actually executes JavaScript (not a fingerprint-spoofing one) clears it the same way a real visitor''s browser does.","Cloudflare WAF hard block: an explicit \"Attention Required!\" page. The site operator has decided automated traffic isn''t welcome, full stop. We treat that as a boundary, not an obstacle.","Akamai hard block: \"Access Denied\" with an x-akamai-cache-status header. Same story as a Cloudflare WAF block: a deliberate access decision, not a technical hurdle to route around.","False positive: the page actually returns a clean 200. One pricing page we''d flagged as blocked turned out to be a stale status from a transient failure, not a real block at all. Worth checking before assuming the worst."]},{"type":"h2","text":"The takeaway"},{"type":"p","text":"Roughly half the scraping failures we''ve diagnosed this way are fixable with better tooling, namely a real headless browser instead of a plain HTTP request. The other half are a site operator''s explicit choice, and no amount of engineering effort should override that. Telling the two apart before writing any code saves you from building something that either doesn''t work or shouldn''t exist in the first place."}]'::jsonb,
  updated_at = now()
where slug = 'why-some-pricing-pages-cant-be-scraped';

update blog_posts set
  title = 'Why competitive intelligence should always be on',
  description = 'Most competitive intelligence still runs as sporadic research before a launch or a QBR. Here''s why that''s the wrong shape, and what "always on" actually requires.',
  body = '[{"type":"p","text":"At most companies, competitive intelligence isn''t a system. It''s a project. Someone builds a battlecard before a big launch or a board meeting, circulates it, and then it sits untouched until the next fire drill sends someone looking again. In between, nobody''s watching."},{"type":"h2","text":"The cost of periodic research"},{"type":"p","text":"The problem with periodic research isn''t quality. It''s that competitors don''t move on your review calendar. A pricing change, a key hire, a funding round: these happen whenever they happen, and by the time your next scheduled competitive review rolls around, the window where that information could have changed a decision has often already closed. A rep can lose a deal to a competitor''s new pricing tier three weeks before anyone on the team even notices it exists."},{"type":"h2","text":"What \"always on\" actually requires"},{"type":"p","text":"Continuous monitoring sounds like it just means checking more often. Doing it well actually requires three separate things:"},{"type":"ul","items":["Continuous data collection. Not a snapshot refreshed occasionally, but sources actually watched on a schedule tight enough to matter.","A way to separate signal from noise. More sources watched more often just means more raw material, not more insight, unless something is doing the filtering.","A fast enough path from \"something changed\" to \"here''s what it means\" that the answer is still useful when it arrives, not a historical footnote by the time someone reads it."]},{"type":"h2","text":"Triage, not tooling"},{"type":"p","text":"Monitoring more sources is, at this point, the easy part. Pricing pages, job boards, press feeds, and social channels have all been crawlable for years. The hard problem is not burying the one signal that matters under fifty that don''t. Turn on monitoring for every competitor across every channel with no way to prioritize what surfaces, and most teams switch it back off within a month, because a noisy feed is worse than no feed at all. That''s the real case for scoring findings against your own business instead of just collecting more of them: always-on only works if it doesn''t also mean always-noisy."}]'::jsonb,
  updated_at = now()
where slug = 'why-competitive-intelligence-should-always-be-on';

update blog_posts set
  title = 'Why most competitive intelligence programs go stale',
  description = 'Battlecards get built once for a launch or a big deal, then rarely touched again. Here''s why maintenance is the part that gets skipped, and what actually keeps intel current.',
  body = '[{"type":"p","text":"Walk into most B2B companies and ask to see the competitive battlecard for their top rival. You''ll usually get one. It''ll usually be six months to a year old, built for a launch or a big deal that closed long ago, with a pricing table that''s quietly wrong and a \"weaknesses\" section describing a product that has since shipped the exact feature it claims the competitor lacks."},{"type":"h2","text":"Why maintenance is the part that gets skipped"},{"type":"p","text":"Creating a battlecard is a project. It has a deadline (the launch, the QBR, the board deck), an owner, and a clear definition of done. Keeping it accurate afterward is a chore with no deadline, no natural owner, and no moment where anyone declares it finished. Projects get staffed; chores mostly don''t. Not because anyone decides competitive intel isn''t worth maintaining, but because nobody ever explicitly decides who''s responsible for noticing when it goes stale."},{"type":"h2","text":"Three ways it actually breaks"},{"type":"ul","items":["No owner after the initial push. Whoever built it moves on to the next launch, and updating a document nobody assigned isn''t anyone''s job.","The underlying facts change quietly. A competitor updates their pricing page or ships a feature with no press release, so there''s no trigger telling anyone to go check.","The team''s attention moves faster than the document does. Three priorities later, the battlecard is a relic of what mattered when it was written, not what matters now."]},{"type":"h2","text":"What keeps intel current, not just created"},{"type":"p","text":"The fix isn''t more discipline or a recurring calendar reminder. Those are exactly the kind of unowned chore that gets skipped the first time someone''s busy, and that''s not a character flaw; it''s just how unassigned recurring work behaves on every team. The real fix is removing the manual step entirely: monitor automatically, and only put something in front of a person when it''s actually worth their attention. Staleness stops being a discipline problem the moment it stops depending on someone remembering."}]'::jsonb,
  updated_at = now()
where slug = 'why-competitive-intelligence-goes-stale';

update blog_posts set
  title = 'What competitive intelligence means in an AI world',
  description = 'AI changed both how fast competitors can move and what''s possible to monitor about them. Here''s what actually changes for competitive intelligence, and what doesn''t.',
  body = '[{"type":"p","text":"Two things changed for competitive intelligence at roughly the same time, and they''re worth separating. Competitors can now ship, reposition, and change pricing faster, because AI tooling compressed their own product cycles. Separately, the tools available for watching them got dramatically more capable, for the same underlying reason."},{"type":"h2","text":"What AI actually changes for the watcher"},{"type":"p","text":"The real shift isn''t philosophical, it''s practical: a handful of things that used to require a person now don''t."},{"type":"ul","items":["Reading and summarizing large volumes of unstructured text (job postings, press coverage, changelogs) cheaply and continuously, instead of a person skimming a handful of sources on a schedule.","Pulling structured facts out of messy pages, like a pricing table or a feature comparison, without someone manually copying numbers into a spreadsheet every time the page changes.","Judging relevance against a specific context, this company''s positioning and its actual win/loss history, instead of applying one generic severity rule to every reader."]},{"type":"h2","text":"What it doesn''t change"},{"type":"p","text":"Judgment about what''s actually true still needs a real source. A model summarizing a rumor still produces a confident-sounding summary of a rumor. Scoring \"does this matter to us\" still requires real context about the reader''s own business. A model can use that context well, but someone has to give it, not have it invented from nothing. More capable summarization of bad or biased inputs is still a bad or biased answer, just delivered more fluently."},{"type":"h2","text":"The actual shift"},{"type":"p","text":"The honest framing isn''t \"AI replaces the competitive intelligence analyst.\" It''s that the cost of running continuous, personalized monitoring dropped enough that \"always on, and scored specifically for us\" is now realistic for a five-person go-to-market team, not just something an enterprise with a dedicated CI function could justify staffing. That access gap closing is the real change, not that the underlying discipline is somehow fundamentally different than it was."}]'::jsonb,
  updated_at = now()
where slug = 'competitive-intelligence-in-an-ai-world';
